### ISSUE TITLE
Clean icon on taskbar doesn't clean the clipboard

### ISSUE THREAD

**Issue by Thewisem** [DeweyReed/ClipboardCleaner#23]
When I click on the clean shortcut on the taskbar, it doesn't clean the clipboard.
Android 7.1.1 nougat

**Comment by DeweyReed** [comment]
Does the app clean the clipboard when you click a shortcut on the home screen?
What soft keyboard app are you using? Does it store your clipboard history?

**Comment by Thewisem** [comment]
The shortcut I mean is like the settings icon on the top of the notification bar. By pressing it, the clipboard stuff is still there.
I am using a samsung device if that helps.

**Comment by DeweyReed** [comment]
I can't reproduce the problem.

Could you see the history of all content you've copied?
What's your Android version?
Are you using the default soft keyboard app? I don't know about Samsung devices, but it appears it stores history, which exceeds ClipboardCleaner's capability.

**Comment by Thewisem** [comment]
1) Yes
2) Android 7.1.1 Nougat
3) I am using Simple Keyboard. Samsung keyboard isn't there in my phones thanks to some tweaking I did.(No my phone isn't rooted)

**Comment by DeweyReed** [comment]
Android system itself doesn't store the history of the content you've copied. Since you can see it, some apps keep it, like your soft keyboard app or a Samsung system app. In either case, it's almost impossible for other apps to modify the history.

You may want to check other apps' settings to try to turn off the history function.

**Comment by Thewisem** [comment]
Hmmm ok
