### ISSUE TITLE
Suggestion to keep previous  copied text visible.

### ISSUE THREAD

**Issue by peerzadaaabid** [DeweyReed/ClipboardCleaner#6]
Hello
I wanna suggest that this ability should not disappear previous text. Sometimes we need to paste the text after copying something else.
So it should be able to store previous text.

Thanks

**Comment by DeweyReed** [comment]
Hello

I don't that's a good idea because this app is called ClipboardCleaner rather than something like ClipboardStoreroom :D

Since Android can only store one clip at a time, it has to override the previous one to store a new one. But I'm sure many other clipboard apps have similar function. Some of them even can share clipboard content and history across devices.

**Comment by DeweyReed** [comment]
I'm closing this issue. Feel free to reopen it if you have other thoughts.
